[pytest]
testpaths = testing
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --cov=. --cov-report=html --cov-report=term --disable-warnings
filterwarnings =
    ignore::DeprecationWarning

[coverage:run]
omit =
    */config-3.py
    */config.py
    testing/*
    */site-packages/*
